FROM {{ namespace }}/{{ image_prefix }}searchlight-base:{{ tag }}
MAINTAINER {{ maintainer }}

COPY extend_start.sh /usr/local/bin/kolla_searchlight_extend_start
RUN chmod 755 /usr/local/bin/kolla_searchlight_extend_start

{{ include_footer }}
